# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LJToolKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LJToolKitDemo

  pod 'MBProgressHUD'

  target 'LJToolKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LJToolKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
